langauge: node_js

node_js:
  - "6"

cache:
  directories:
    - node_modules

script:
  - npm run coverage

notifications:
  email:
    on_success: never
    on_failure: change

before_install:
  - pip install --user codecov

after_success:
  - codecov --file coverage/lcov.info --disable search
