sudo: false

language: node_js
node_js:
  - "6"

cache:
  directories:
    - node_modules

script: npm run coverage

before_install:
  #- npm install codecov.io
  - npm install coveralls

after_success:
#  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

branches:
  only:
    - master

notifications:
  email:
    on_success: never
    on_failure: change
